# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enigma_ui(object):
    def setupUi(self, Enigma_ui):
        Enigma_ui.setObjectName("Enigma_ui")
        Enigma_ui.resize(750, 610)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Enigma_ui.sizePolicy().hasHeightForWidth())
        Enigma_ui.setSizePolicy(sizePolicy)
        Enigma_ui.setMinimumSize(QtCore.QSize(750, 610))
        Enigma_ui.setMaximumSize(QtCore.QSize(750, 610))
        self.debugTextBrowser = QtWidgets.QTextBrowser(Enigma_ui)
        self.debugTextBrowser.setGeometry(QtCore.QRect(20, 390, 710, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debugTextBrowser.sizePolicy().hasHeightForWidth())
        self.debugTextBrowser.setSizePolicy(sizePolicy)
        self.debugTextBrowser.setObjectName("debugTextBrowser")
        self.enigma_label = QtWidgets.QLabel(Enigma_ui)
        self.enigma_label.setGeometry(QtCore.QRect(20, 10, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.enigma_label.setFont(font)
        self.enigma_label.setAlignment(QtCore.Qt.AlignCenter)
        self.enigma_label.setWordWrap(False)
        self.enigma_label.setObjectName("enigma_label")
        self.main_frame = QtWidgets.QFrame(Enigma_ui)
        self.main_frame.setGeometry(QtCore.QRect(20, 40, 711, 271))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.browse_file_label = QtWidgets.QLabel(self.main_frame)
        self.browse_file_label.setGeometry(QtCore.QRect(10, 10, 691, 21))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.browse_file_label.setFont(font)
        self.browse_file_label.setAlignment(QtCore.Qt.AlignCenter)
        self.browse_file_label.setObjectName("browse_file_label")
        self.layoutWidget = QtWidgets.QWidget(self.main_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 40, 711, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.browse_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.browse_layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.browse_layout.setContentsMargins(0, 0, 0, 0)
        self.browse_layout.setSpacing(8)
        self.browse_layout.setObjectName("browse_layout")
        self.browse_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.browse_line.setText("")
        self.browse_line.setMaxLength(100)
        self.browse_line.setAlignment(QtCore.Qt.AlignCenter)
        self.browse_line.setObjectName("browse_line")
        self.browse_layout.addWidget(self.browse_line)
        self.browse_button = QtWidgets.QPushButton(self.layoutWidget)
        self.browse_button.setEnabled(True)
        self.browse_button.setIconSize(QtCore.QSize(18, 16))
        self.browse_button.setObjectName("browse_button")
        self.browse_layout.addWidget(self.browse_button)
        self.layoutWidget1 = QtWidgets.QWidget(self.main_frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 200, 711, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.steckerbrett_layout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.steckerbrett_layout.setContentsMargins(0, 0, 0, 0)
        self.steckerbrett_layout.setObjectName("steckerbrett_layout")
        self.steckerbret_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.steckerbret_label.setFont(font)
        self.steckerbret_label.setAlignment(QtCore.Qt.AlignCenter)
        self.steckerbret_label.setObjectName("steckerbret_label")
        self.steckerbrett_layout.addWidget(self.steckerbret_label)
        self.steckerbrett_values = QtWidgets.QLineEdit(self.layoutWidget1)
        self.steckerbrett_values.setObjectName("steckerbrett_values")
        self.steckerbrett_layout.addWidget(self.steckerbrett_values)
        self.layoutWidget2 = QtWidgets.QWidget(self.main_frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 100, 711, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.rotor_layout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.rotor_layout.setContentsMargins(0, 0, 0, 0)
        self.rotor_layout.setObjectName("rotor_layout")
        self.rotor_settings_label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rotor_settings_label.setFont(font)
        self.rotor_settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotor_settings_label.setObjectName("rotor_settings_label")
        self.rotor_layout.addWidget(self.rotor_settings_label)
        self.rotor_settings_layout = QtWidgets.QHBoxLayout()
        self.rotor_settings_layout.setSpacing(20)
        self.rotor_settings_layout.setObjectName("rotor_settings_layout")
        self.rotor_setting_alpha_layout = QtWidgets.QVBoxLayout()
        self.rotor_setting_alpha_layout.setObjectName("rotor_setting_alpha_layout")
        self.alpha_label = QtWidgets.QLabel(self.layoutWidget2)
        self.alpha_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_label.setObjectName("alpha_label")
        self.rotor_setting_alpha_layout.addWidget(self.alpha_label)
        self.alpha_combo = QtWidgets.QComboBox(self.layoutWidget2)
        self.alpha_combo.setObjectName("alpha_combo")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.alpha_combo.addItem("")
        self.rotor_setting_alpha_layout.addWidget(self.alpha_combo)
        self.rotor_settings_layout.addLayout(self.rotor_setting_alpha_layout)
        self.rotor_setting_beta_layout = QtWidgets.QVBoxLayout()
        self.rotor_setting_beta_layout.setObjectName("rotor_setting_beta_layout")
        self.beta_label = QtWidgets.QLabel(self.layoutWidget2)
        self.beta_label.setAlignment(QtCore.Qt.AlignCenter)
        self.beta_label.setObjectName("beta_label")
        self.rotor_setting_beta_layout.addWidget(self.beta_label)
        self.beta_combo = QtWidgets.QComboBox(self.layoutWidget2)
        self.beta_combo.setObjectName("beta_combo")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.beta_combo.addItem("")
        self.rotor_setting_beta_layout.addWidget(self.beta_combo)
        self.rotor_settings_layout.addLayout(self.rotor_setting_beta_layout)
        self.rotor_setting_gama_layout = QtWidgets.QVBoxLayout()
        self.rotor_setting_gama_layout.setObjectName("rotor_setting_gama_layout")
        self.gama_label = QtWidgets.QLabel(self.layoutWidget2)
        self.gama_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gama_label.setObjectName("gama_label")
        self.rotor_setting_gama_layout.addWidget(self.gama_label)
        self.gama_combo = QtWidgets.QComboBox(self.layoutWidget2)
        self.gama_combo.setObjectName("gama_combo")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.gama_combo.addItem("")
        self.rotor_setting_gama_layout.addWidget(self.gama_combo)
        self.rotor_settings_layout.addLayout(self.rotor_setting_gama_layout)
        self.rotor_layout.addLayout(self.rotor_settings_layout)
        self.start_button = QtWidgets.QPushButton(Enigma_ui)
        self.start_button.setGeometry(QtCore.QRect(20, 330, 711, 41))
        self.start_button.setObjectName("start_button")
        self.layoutWidget_2 = QtWidgets.QWidget(Enigma_ui)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 570, 711, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.export_layout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.export_layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.export_layout.setContentsMargins(0, 0, 0, 0)
        self.export_layout.setSpacing(8)
        self.export_layout.setObjectName("export_layout")
        self.export_line = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.export_line.setText("")
        self.export_line.setMaxLength(100)
        self.export_line.setAlignment(QtCore.Qt.AlignCenter)
        self.export_line.setObjectName("export_line")
        self.export_layout.addWidget(self.export_line)
        self.export_button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.export_button.setEnabled(True)
        self.export_button.setIconSize(QtCore.QSize(18, 16))
        self.export_button.setObjectName("export_button")
        self.export_layout.addWidget(self.export_button)

        self.retranslateUi(Enigma_ui)
        QtCore.QMetaObject.connectSlotsByName(Enigma_ui)

    def retranslateUi(self, Enigma_ui):
        _translate = QtCore.QCoreApplication.translate
        Enigma_ui.setWindowTitle(_translate("Enigma_ui", "Enigma_ui"))
        self.enigma_label.setText(_translate("Enigma_ui", "Enigma Machine Simulator"))
        self.browse_file_label.setText(_translate("Enigma_ui", "Browse .txt file that you want to insert into Enigma"))
        self.browse_button.setText(_translate("Enigma_ui", "Browse"))
        self.steckerbret_label.setText(_translate("Enigma_ui", "Insert Steckerbrett values"))
        self.rotor_settings_label.setText(_translate("Enigma_ui", "Insert initial Rotor settings"))
        self.alpha_label.setText(_translate("Enigma_ui", "Alpha Rotor"))
        self.alpha_combo.setItemText(0, _translate("Enigma_ui", "0"))
        self.alpha_combo.setItemText(1, _translate("Enigma_ui", "1"))
        self.alpha_combo.setItemText(2, _translate("Enigma_ui", "2"))
        self.alpha_combo.setItemText(3, _translate("Enigma_ui", "3"))
        self.alpha_combo.setItemText(4, _translate("Enigma_ui", "4"))
        self.alpha_combo.setItemText(5, _translate("Enigma_ui", "5"))
        self.alpha_combo.setItemText(6, _translate("Enigma_ui", "6"))
        self.alpha_combo.setItemText(7, _translate("Enigma_ui", "7"))
        self.alpha_combo.setItemText(8, _translate("Enigma_ui", "8"))
        self.alpha_combo.setItemText(9, _translate("Enigma_ui", "9"))
        self.alpha_combo.setItemText(10, _translate("Enigma_ui", "10"))
        self.alpha_combo.setItemText(11, _translate("Enigma_ui", "11"))
        self.alpha_combo.setItemText(12, _translate("Enigma_ui", "12"))
        self.alpha_combo.setItemText(13, _translate("Enigma_ui", "13"))
        self.alpha_combo.setItemText(14, _translate("Enigma_ui", "14"))
        self.alpha_combo.setItemText(15, _translate("Enigma_ui", "15"))
        self.alpha_combo.setItemText(16, _translate("Enigma_ui", "16"))
        self.alpha_combo.setItemText(17, _translate("Enigma_ui", "17"))
        self.alpha_combo.setItemText(18, _translate("Enigma_ui", "18"))
        self.alpha_combo.setItemText(19, _translate("Enigma_ui", "19"))
        self.alpha_combo.setItemText(20, _translate("Enigma_ui", "20"))
        self.alpha_combo.setItemText(21, _translate("Enigma_ui", "21"))
        self.alpha_combo.setItemText(22, _translate("Enigma_ui", "22"))
        self.alpha_combo.setItemText(23, _translate("Enigma_ui", "23"))
        self.alpha_combo.setItemText(24, _translate("Enigma_ui", "24"))
        self.alpha_combo.setItemText(25, _translate("Enigma_ui", "25"))
        self.alpha_combo.setItemText(26, _translate("Enigma_ui", "26"))
        self.beta_label.setText(_translate("Enigma_ui", "Beta Rotor"))
        self.beta_combo.setItemText(0, _translate("Enigma_ui", "0"))
        self.beta_combo.setItemText(1, _translate("Enigma_ui", "1"))
        self.beta_combo.setItemText(2, _translate("Enigma_ui", "2"))
        self.beta_combo.setItemText(3, _translate("Enigma_ui", "3"))
        self.beta_combo.setItemText(4, _translate("Enigma_ui", "4"))
        self.beta_combo.setItemText(5, _translate("Enigma_ui", "5"))
        self.beta_combo.setItemText(6, _translate("Enigma_ui", "6"))
        self.beta_combo.setItemText(7, _translate("Enigma_ui", "7"))
        self.beta_combo.setItemText(8, _translate("Enigma_ui", "8"))
        self.beta_combo.setItemText(9, _translate("Enigma_ui", "9"))
        self.beta_combo.setItemText(10, _translate("Enigma_ui", "10"))
        self.beta_combo.setItemText(11, _translate("Enigma_ui", "11"))
        self.beta_combo.setItemText(12, _translate("Enigma_ui", "12"))
        self.beta_combo.setItemText(13, _translate("Enigma_ui", "13"))
        self.beta_combo.setItemText(14, _translate("Enigma_ui", "14"))
        self.beta_combo.setItemText(15, _translate("Enigma_ui", "15"))
        self.beta_combo.setItemText(16, _translate("Enigma_ui", "16"))
        self.beta_combo.setItemText(17, _translate("Enigma_ui", "17"))
        self.beta_combo.setItemText(18, _translate("Enigma_ui", "18"))
        self.beta_combo.setItemText(19, _translate("Enigma_ui", "19"))
        self.beta_combo.setItemText(20, _translate("Enigma_ui", "20"))
        self.beta_combo.setItemText(21, _translate("Enigma_ui", "21"))
        self.beta_combo.setItemText(22, _translate("Enigma_ui", "22"))
        self.beta_combo.setItemText(23, _translate("Enigma_ui", "23"))
        self.beta_combo.setItemText(24, _translate("Enigma_ui", "24"))
        self.beta_combo.setItemText(25, _translate("Enigma_ui", "25"))
        self.beta_combo.setItemText(26, _translate("Enigma_ui", "26"))
        self.gama_label.setText(_translate("Enigma_ui", "Gama Rotor"))
        self.gama_combo.setItemText(0, _translate("Enigma_ui", "0"))
        self.gama_combo.setItemText(1, _translate("Enigma_ui", "1"))
        self.gama_combo.setItemText(2, _translate("Enigma_ui", "2"))
        self.gama_combo.setItemText(3, _translate("Enigma_ui", "3"))
        self.gama_combo.setItemText(4, _translate("Enigma_ui", "4"))
        self.gama_combo.setItemText(5, _translate("Enigma_ui", "5"))
        self.gama_combo.setItemText(6, _translate("Enigma_ui", "6"))
        self.gama_combo.setItemText(7, _translate("Enigma_ui", "7"))
        self.gama_combo.setItemText(8, _translate("Enigma_ui", "8"))
        self.gama_combo.setItemText(9, _translate("Enigma_ui", "9"))
        self.gama_combo.setItemText(10, _translate("Enigma_ui", "10"))
        self.gama_combo.setItemText(11, _translate("Enigma_ui", "11"))
        self.gama_combo.setItemText(12, _translate("Enigma_ui", "12"))
        self.gama_combo.setItemText(13, _translate("Enigma_ui", "13"))
        self.gama_combo.setItemText(14, _translate("Enigma_ui", "14"))
        self.gama_combo.setItemText(15, _translate("Enigma_ui", "15"))
        self.gama_combo.setItemText(16, _translate("Enigma_ui", "16"))
        self.gama_combo.setItemText(17, _translate("Enigma_ui", "17"))
        self.gama_combo.setItemText(18, _translate("Enigma_ui", "18"))
        self.gama_combo.setItemText(19, _translate("Enigma_ui", "19"))
        self.gama_combo.setItemText(20, _translate("Enigma_ui", "20"))
        self.gama_combo.setItemText(21, _translate("Enigma_ui", "21"))
        self.gama_combo.setItemText(22, _translate("Enigma_ui", "22"))
        self.gama_combo.setItemText(23, _translate("Enigma_ui", "23"))
        self.gama_combo.setItemText(24, _translate("Enigma_ui", "24"))
        self.gama_combo.setItemText(25, _translate("Enigma_ui", "25"))
        self.gama_combo.setItemText(26, _translate("Enigma_ui", "26"))
        self.start_button.setText(_translate("Enigma_ui", "START MACHINE"))
        self.export_button.setText(_translate("Enigma_ui", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Enigma_ui = QtWidgets.QWidget()
    ui = Ui_Enigma_ui()
    ui.setupUi(Enigma_ui)
    Enigma_ui.show()
    sys.exit(app.exec_())
